/**
 * Contract: @toride/codegen output after type safety improvements.
 *
 * Example of what codegen produces for a policy with:
 * - Actors: User (email: string, is_admin: boolean)
 * - Resources: Document (status: string, ownerId: string), Organization (plan: string)
 * - Relations: Document.org -> Organization
 */

// Auto-generated by @toride/codegen — do not edit

import type { TorideSchema } from "toride";

/** All action strings declared across all resources */
export type Actions = "read" | "write" | "delete" | "manage";

/** All resource type names */
export type Resources = "Document" | "Organization";

/** All actor type names */
export type ActorTypes = "User";

/** Per-resource role types */
export interface RoleMap {
  Document: "owner" | "editor" | "viewer";
  Organization: "admin" | "member";
}

/** Per-resource permission types */
export interface PermissionMap {
  Document: "read" | "write" | "delete";
  Organization: "manage" | "read";
}

/** Per-resource attribute types (NEW — from resource attributes declarations) */
export interface ResourceAttributeMap {
  Document: { status: string; ownerId: string };
  Organization: { plan: string };
}

/** Per-actor attribute types (NEW — from actor attribute declarations) */
export interface ActorAttributeMap {
  User: { email: string; is_admin: boolean };
}

/** Relation map — resource type -> relation name -> target resource type */
export interface RelationMap {
  Document: {
    org: "Organization";
  };
  Organization: Record<string, never>;
}

/** Per-type resolver map — typed return values match resource attributes */
export type ResolverMap = {
  [R in Resources]?: (
    ref: { type: R; id: string; attributes?: ResourceAttributeMap[R] },
  ) => Promise<ResourceAttributeMap[R]>;
};

/**
 * Unified schema interface — pass this as Toride<GeneratedSchema>.
 * Aggregates all type maps into the TorideSchema shape.
 */
export interface GeneratedSchema extends TorideSchema {
  resources: Resources;
  actions: Actions;
  actorTypes: ActorTypes;
  permissionMap: PermissionMap;
  roleMap: RoleMap;
  resourceAttributeMap: ResourceAttributeMap;
  actorAttributeMap: ActorAttributeMap;
  relationMap: RelationMap;
}
