import { describe, it, expect } from "vitest";
import type { Policy } from "toride";
import { generateTypes } from "../src/generator.js";

function makePolicy(overrides: Partial<Policy> = {}): Policy {
  return {
    version: "1",
    actors: {
      User: { attributes: { email: "string", department: "string" } },
    },
    resources: {
      Project: {
        roles: ["viewer", "editor", "admin"],
        permissions: ["read", "update", "delete", "create_task"],
        relations: {
          org: { resource: "Organization", cardinality: "one" as const },
        },
        grants: {
          viewer: ["read"],
          editor: ["read", "update", "create_task"],
          admin: ["all"],
        },
      },
      Task: {
        roles: ["viewer", "editor"],
        permissions: ["read", "update", "delete"],
        relations: {
          project: { resource: "Project", cardinality: "one" as const },
          assignee: { resource: "User", cardinality: "one" as const },
        },
        grants: {
          viewer: ["read"],
          editor: ["read", "update", "delete"],
        },
      },
    },
    ...overrides,
  };
}

describe("generateTypes", () => {
  it("produces a string containing the auto-generated header", () => {
    const output = generateTypes(makePolicy());
    expect(output).toContain("Auto-generated by @toride/codegen");
    expect(output).toContain("do not edit");
  });

  it("generates Actions type as union of all unique permissions", () => {
    const output = generateTypes(makePolicy());
    expect(output).toContain("export type Actions =");
    expect(output).toMatch(/"read"/);
    expect(output).toMatch(/"update"/);
    expect(output).toMatch(/"delete"/);
    expect(output).toMatch(/"create_task"/);
  });

  it("generates Resources type as union of all resource names", () => {
    const output = generateTypes(makePolicy());
    expect(output).toContain("export type Resources =");
    expect(output).toMatch(/"Project"/);
    expect(output).toMatch(/"Task"/);
  });

  it("generates RoleMap interface with per-resource role unions", () => {
    const output = generateTypes(makePolicy());
    expect(output).toContain("export interface RoleMap");
    expect(output).toMatch(/Project:\s*"viewer"\s*\|\s*"editor"\s*\|\s*"admin"/);
    expect(output).toMatch(/Task:\s*"viewer"\s*\|\s*"editor"/);
  });

  it("generates PermissionMap interface with per-resource permission unions", () => {
    const output = generateTypes(makePolicy());
    expect(output).toContain("export interface PermissionMap");
    expect(output).toMatch(/Project:\s*"read"\s*\|\s*"update"\s*\|\s*"delete"\s*\|\s*"create_task"/);
    expect(output).toMatch(/Task:\s*"read"\s*\|\s*"update"\s*\|\s*"delete"/);
  });

  it("generates RelationMap interface with relation details", () => {
    const output = generateTypes(makePolicy());
    expect(output).toContain("export interface RelationMap");
    expect(output).toMatch(/Project:/);
    expect(output).toMatch(/org.*type.*"Organization".*cardinality.*"one"/s);
    expect(output).toMatch(/Task:/);
    expect(output).toMatch(/project.*type.*"Project".*cardinality.*"one"/s);
    expect(output).toMatch(/assignee.*type.*"User".*cardinality.*"one"/s);
  });

  it("handles resources with no relations", () => {
    const policy = makePolicy({
      resources: {
        Simple: {
          roles: ["viewer"],
          permissions: ["read"],
          grants: { viewer: ["read"] },
        },
      },
    });
    const output = generateTypes(policy);
    expect(output).toContain("export interface RelationMap");
    // Simple should have an empty or Record<string, never> entry
    expect(output).toMatch(/Simple:/);
  });

  it("handles empty resources", () => {
    const policy = makePolicy({ resources: {} });
    const output = generateTypes(policy);
    expect(output).toContain("export type Actions = never");
    expect(output).toContain("export type Resources = never");
  });

  it("generates TypedRelationResolver interface", () => {
    const output = generateTypes(makePolicy());
    expect(output).toContain("export interface TypedRelationResolver");
    expect(output).toContain("getRelated");
    expect(output).toContain("getRoles");
    expect(output).toContain("getAttributes");
  });

  it("produces valid TypeScript (no syntax errors)", () => {
    const output = generateTypes(makePolicy());
    // Basic structural checks
    expect(output).toMatch(/^\/\//m); // Has comment
    const openBraces = (output.match(/{/g) || []).length;
    const closeBraces = (output.match(/}/g) || []).length;
    expect(openBraces).toBe(closeBraces); // Balanced braces
  });
});
