// T098: @toride/codegen generator
// Generates TypeScript type declarations from a toride Policy

import type { ActorDeclaration, AttributeType, Policy, ResourceBlock } from "toride";

/**
 * Generate TypeScript type declarations from a toride policy.
 *
 * Emits (in order):
 * - import type { TorideSchema } from "toride"
 * - Actions: union of all unique permission strings
 * - Resources: union of all resource type names
 * - ActorTypes: union of all actor type names
 * - RoleMap: per-resource role union types
 * - PermissionMap: per-resource permission union types
 * - ResourceAttributeMap: per-resource attribute types
 * - ActorAttributeMap: per-actor attribute types
 * - RelationMap: per-resource relation target types
 * - ResolverMap: typed per-type resolver map
 * - GeneratedSchema: unified schema interface extending TorideSchema
 */
/** Safe identifier pattern: alphanumeric + underscore, starting with a letter or underscore */
const SAFE_IDENTIFIER = /^[A-Za-z_][A-Za-z0-9_]*$/;

/** Supported attribute type mappings */
const ATTRIBUTE_TYPE_MAP: Record<AttributeType, string> = {
  string: "string",
  number: "number",
  boolean: "boolean",
};

/** Escape quotes and backslashes for safe string interpolation into TypeScript string literals */
function escapeStringLiteral(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/** Validate that a string is a safe TypeScript identifier, throw if not */
function assertSafeIdentifier(s: string, context: string): void {
  if (!SAFE_IDENTIFIER.test(s)) {
    throw new Error(
      `Unsafe identifier in ${context}: "${escapeStringLiteral(s)}". ` +
      `Identifiers must match ${SAFE_IDENTIFIER.source}`,
    );
  }
}

/** Map an AttributeType to its TypeScript type string */
function mapAttributeType(attrType: string, context: string): string {
  const mapped = ATTRIBUTE_TYPE_MAP[attrType as AttributeType];
  if (!mapped) {
    throw new Error(
      `Unknown attribute type "${escapeStringLiteral(attrType)}" in ${context}. ` +
      `Supported types: ${Object.keys(ATTRIBUTE_TYPE_MAP).join(", ")}`,
    );
  }
  return mapped;
}

/** Generate attribute type literal for a record of attribute declarations */
function generateAttributeFields(
  attrs: Record<string, AttributeType>,
  entityType: string,
  entityName: string,
): string {
  const fields = Object.entries(attrs)
    .map(([k, v]) => `${k}: ${mapAttributeType(v, `attribute "${k}" in ${entityType} "${entityName}"`)}`)
    .join("; ");
  return `{ ${fields}; }`;
}

export function generateTypes(policy: Policy): string {
  const resourceEntries: [string, ResourceBlock][] = Object.entries(policy.resources);
  const actorEntries: [string, ActorDeclaration][] = Object.entries(policy.actors);
  const resourceNames = resourceEntries.map(([name]) => name);
  const actorNames = actorEntries.map(([name]) => name);
  const lines: string[] = [];

  lines.push("// Auto-generated by @toride/codegen — do not edit");
  lines.push("");
  lines.push('import type { TorideSchema } from "toride";');
  lines.push("");

  // Validate all identifiers before generating code
  for (const name of resourceNames) {
    assertSafeIdentifier(name, "resource name");
  }
  for (const [rName, block] of resourceEntries) {
    for (const role of block.roles) {
      assertSafeIdentifier(role, `role in resource "${rName}"`);
    }
    for (const perm of block.permissions) {
      assertSafeIdentifier(perm, `permission in resource "${rName}"`);
    }
    if (block.relations) {
      for (const [relName, relDef] of Object.entries(block.relations) as [string, string][]) {
        assertSafeIdentifier(relName, `relation name in resource "${rName}"`);
        assertSafeIdentifier(relDef, `relation target in resource "${rName}"`);
      }
    }
    if (block.attributes) {
      for (const [attrName, attrType] of Object.entries(block.attributes) as [string, string][]) {
        assertSafeIdentifier(attrName, `attribute name in resource "${rName}"`);
        mapAttributeType(attrType, `attribute "${attrName}" in resource "${rName}"`);
      }
    }
  }
  for (const [actorName, actorDecl] of actorEntries) {
    assertSafeIdentifier(actorName, "actor type name");
    for (const [attrName, attrType] of Object.entries(actorDecl.attributes) as [string, string][]) {
      assertSafeIdentifier(attrName, `attribute name in actor "${actorName}"`);
      mapAttributeType(attrType, `attribute "${attrName}" in actor "${actorName}"`);
    }
  }

  // Collect all unique actions
  const allActions = new Set<string>();
  for (const [, block] of resourceEntries) {
    for (const perm of block.permissions) {
      allActions.add(perm);
    }
  }

  // Actions type
  lines.push(`/** All action strings declared across all resources */`);
  if (allActions.size === 0) {
    lines.push("export type Actions = never;");
  } else {
    const actionUnion = [...allActions].map((a) => `"${a}"`).join(" | ");
    lines.push(`export type Actions = ${actionUnion};`);
  }
  lines.push("");

  // Resources type
  lines.push(`/** All resource type names */`);
  if (resourceNames.length === 0) {
    lines.push("export type Resources = never;");
  } else {
    const resourceUnion = resourceNames.map((r) => `"${r}"`).join(" | ");
    lines.push(`export type Resources = ${resourceUnion};`);
  }
  lines.push("");

  // ActorTypes type
  lines.push(`/** All actor type names */`);
  if (actorNames.length === 0) {
    lines.push("export type ActorTypes = never;");
  } else {
    const actorUnion = actorNames.map((a) => `"${a}"`).join(" | ");
    lines.push(`export type ActorTypes = ${actorUnion};`);
  }
  lines.push("");

  // RoleMap
  lines.push(`/** Per-resource role types */`);
  lines.push(`export interface RoleMap {`);
  for (const [name, block] of resourceEntries) {
    if (block.roles.length > 0) {
      const roleUnion = block.roles.map((r: string) => `"${r}"`).join(" | ");
      lines.push(`  ${name}: ${roleUnion};`);
    } else {
      lines.push(`  ${name}: never;`);
    }
  }
  lines.push(`}`);
  lines.push("");

  // PermissionMap
  lines.push(`/** Per-resource permission types */`);
  lines.push(`export interface PermissionMap {`);
  for (const [name, block] of resourceEntries) {
    if (block.permissions.length > 0) {
      const permUnion = block.permissions.map((p: string) => `"${p}"`).join(" | ");
      lines.push(`  ${name}: ${permUnion};`);
    } else {
      lines.push(`  ${name}: never;`);
    }
  }
  lines.push(`}`);
  lines.push("");

  // ResourceAttributeMap
  lines.push(`/** Per-resource attribute types */`);
  lines.push(`export interface ResourceAttributeMap {`);
  for (const [name, block] of resourceEntries) {
    if (block.attributes && Object.keys(block.attributes).length > 0) {
      lines.push(`  ${name}: ${generateAttributeFields(block.attributes, "resource", name)};`);
    } else {
      lines.push(`  ${name}: Record<string, unknown>;`);
    }
  }
  lines.push(`}`);
  lines.push("");

  // ActorAttributeMap
  lines.push(`/** Per-actor attribute types */`);
  lines.push(`export interface ActorAttributeMap {`);
  for (const [name, actorDecl] of actorEntries) {
    const attrKeys = Object.keys(actorDecl.attributes);
    if (attrKeys.length > 0) {
      lines.push(`  ${name}: ${generateAttributeFields(actorDecl.attributes, "actor", name)};`);
    } else {
      lines.push(`  ${name}: Record<string, unknown>;`);
    }
  }
  lines.push(`}`);
  lines.push("");

  // RelationMap
  lines.push(`/** Relation map — resource type -> relation name -> target resource type */`);
  lines.push(`export interface RelationMap {`);
  for (const [name, block] of resourceEntries) {
    const relations = block.relations ?? {};
    const relEntries = Object.entries(relations);
    if (relEntries.length === 0) {
      lines.push(`  ${name}: Record<string, never>;`);
    } else {
      lines.push(`  ${name}: {`);
      for (const [relName, relDef] of relEntries) {
        lines.push(`    ${relName}: "${relDef}";`);
      }
      lines.push(`  };`);
    }
  }
  lines.push(`}`);
  lines.push("");

  // ResolverMap
  lines.push(`/** Per-type resolver map — typed return values match resource attributes */`);
  lines.push(`export type ResolverMap = {`);
  lines.push(`  [R in Resources]?: (`);
  lines.push(`    ref: { type: R; id: string; attributes?: ResourceAttributeMap[R] },`);
  lines.push(`  ) => Promise<ResourceAttributeMap[R]>;`);
  lines.push(`};`);
  lines.push("");

  // GeneratedSchema
  lines.push(`/**`);
  lines.push(` * Unified schema interface — pass this as Toride<GeneratedSchema>.`);
  lines.push(` * Aggregates all type maps into the TorideSchema shape.`);
  lines.push(` */`);
  lines.push(`export interface GeneratedSchema extends TorideSchema {`);
  lines.push(`  resources: Resources;`);
  lines.push(`  actions: Actions;`);
  lines.push(`  actorTypes: ActorTypes;`);
  lines.push(`  permissionMap: PermissionMap;`);
  lines.push(`  roleMap: RoleMap;`);
  lines.push(`  resourceAttributeMap: ResourceAttributeMap;`);
  lines.push(`  actorAttributeMap: ActorAttributeMap;`);
  lines.push(`  relationMap: RelationMap;`);
  lines.push(`}`);
  lines.push("");

  return lines.join("\n");
}
