// T098: @toride/codegen generator
// Generates TypeScript type declarations from a toride Policy

import type { Policy, ResourceBlock } from "toride";

/**
 * Generate TypeScript type declarations from a toride policy.
 *
 * Emits:
 * - Actions: union of all unique permission strings
 * - Resources: union of all resource type names
 * - RoleMap: per-resource role union types
 * - PermissionMap: per-resource permission union types
 * - RelationMap: per-resource relation target types
 * - TypedResolvers: typed per-type resolver map
 */
/** Safe identifier pattern: alphanumeric + underscore, starting with a letter or underscore */
const SAFE_IDENTIFIER = /^[A-Za-z_][A-Za-z0-9_]*$/;

/** Escape quotes and backslashes for safe string interpolation into TypeScript string literals */
function escapeStringLiteral(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/** Validate that a string is a safe TypeScript identifier, throw if not */
function assertSafeIdentifier(s: string, context: string): void {
  if (!SAFE_IDENTIFIER.test(s)) {
    throw new Error(
      `Unsafe identifier in ${context}: "${escapeStringLiteral(s)}". ` +
      `Identifiers must match ${SAFE_IDENTIFIER.source}`,
    );
  }
}

export function generateTypes(policy: Policy): string {
  const resourceNames = Object.keys(policy.resources);
  const lines: string[] = [];

  lines.push("// Auto-generated by @toride/codegen — do not edit");
  lines.push("");

  // Validate all identifiers before generating code
  for (const name of resourceNames) {
    assertSafeIdentifier(name, "resource name");
  }
  for (const [rName, block] of Object.entries(policy.resources)) {
    for (const role of block.roles) {
      assertSafeIdentifier(role, `role in resource "${rName}"`);
    }
    for (const perm of block.permissions) {
      assertSafeIdentifier(perm, `permission in resource "${rName}"`);
    }
    if (block.relations) {
      for (const [relName, relDef] of Object.entries(block.relations)) {
        assertSafeIdentifier(relName, `relation name in resource "${rName}"`);
        assertSafeIdentifier(relDef, `relation target in resource "${rName}"`);
      }
    }
  }

  // Collect all unique actions and resource names
  const allActions = new Set<string>();
  for (const block of Object.values(policy.resources)) {
    for (const perm of block.permissions) {
      allActions.add(perm);
    }
  }

  // Actions type
  lines.push(`/** All action strings declared across all resources */`);
  if (allActions.size === 0) {
    lines.push("export type Actions = never;");
  } else {
    const actionUnion = [...allActions].map((a) => `"${a}"`).join(" | ");
    lines.push(`export type Actions = ${actionUnion};`);
  }
  lines.push("");

  // Resources type
  lines.push(`/** All resource type names */`);
  if (resourceNames.length === 0) {
    lines.push("export type Resources = never;");
  } else {
    const resourceUnion = resourceNames.map((r) => `"${r}"`).join(" | ");
    lines.push(`export type Resources = ${resourceUnion};`);
  }
  lines.push("");

  // RoleMap
  lines.push(`/** Per-resource role types */`);
  lines.push(`export interface RoleMap {`);
  for (const [name, block] of Object.entries(policy.resources)) {
    if (block.roles.length > 0) {
      const roleUnion = block.roles.map((r) => `"${r}"`).join(" | ");
      lines.push(`  ${name}: ${roleUnion};`);
    } else {
      lines.push(`  ${name}: never;`);
    }
  }
  lines.push(`}`);
  lines.push("");

  // PermissionMap
  lines.push(`/** Per-resource permission types */`);
  lines.push(`export interface PermissionMap {`);
  for (const [name, block] of Object.entries(policy.resources)) {
    if (block.permissions.length > 0) {
      const permUnion = block.permissions.map((p) => `"${p}"`).join(" | ");
      lines.push(`  ${name}: ${permUnion};`);
    } else {
      lines.push(`  ${name}: never;`);
    }
  }
  lines.push(`}`);
  lines.push("");

  // RelationMap
  lines.push(`/** Relation map — resource type -> relation name -> target resource type */`);
  lines.push(`export interface RelationMap {`);
  for (const [name, block] of Object.entries(policy.resources)) {
    const relations = block.relations ?? {};
    const relEntries = Object.entries(relations);
    if (relEntries.length === 0) {
      lines.push(`  ${name}: Record<string, never>;`);
    } else {
      lines.push(`  ${name}: {`);
      for (const [relName, relDef] of relEntries) {
        lines.push(`    ${relName}: "${relDef}";`);
      }
      lines.push(`  };`);
    }
  }
  lines.push(`}`);
  lines.push("");

  // TypedResolvers
  lines.push(`/** Typed per-type resolvers — TypeScript errors if you miss a resource type */`);
  lines.push(`export type TypedResolvers = {`);
  lines.push(`  [R in keyof RelationMap]?: (`);
  lines.push(`    ref: { type: R; id: string; attributes?: Record<string, unknown> }`);
  lines.push(`  ) => Promise<Record<string, unknown>>;`);
  lines.push(`};`);
  lines.push("");

  return lines.join("\n");
}
