import { describe, it, expect } from "vitest";
import type { Policy } from "toride";
import { generateTypes } from "./generator.js";

function makePolicy(overrides: Partial<Policy> = {}): Policy {
  return {
    version: "1",
    actors: {
      User: { attributes: { email: "string", department: "string" } },
    },
    resources: {
      Project: {
        roles: ["viewer", "editor", "admin"],
        permissions: ["read", "update", "delete", "create_task"],
        attributes: { status: "string", priority: "number" },
        relations: {
          org: "Organization",
        },
        grants: {
          viewer: ["read"],
          editor: ["read", "update", "create_task"],
          admin: ["all"],
        },
      },
      Task: {
        roles: ["viewer", "editor"],
        permissions: ["read", "update", "delete"],
        relations: {
          project: "Project",
          assignee: "User",
        },
        grants: {
          viewer: ["read"],
          editor: ["read", "update", "delete"],
        },
      },
    },
    ...overrides,
  };
}

describe("generateTypes", () => {
  it("produces a string containing the auto-generated header", () => {
    const output = generateTypes(makePolicy());
    expect(output).toContain("Auto-generated by @toride/codegen");
    expect(output).toContain("do not edit");
  });

  it("generates Actions type as union of all unique permissions", () => {
    const output = generateTypes(makePolicy());
    expect(output).toContain("export type Actions =");
    expect(output).toMatch(/"read"/);
    expect(output).toMatch(/"update"/);
    expect(output).toMatch(/"delete"/);
    expect(output).toMatch(/"create_task"/);
  });

  it("generates Resources type as union of all resource names", () => {
    const output = generateTypes(makePolicy());
    expect(output).toContain("export type Resources =");
    expect(output).toMatch(/"Project"/);
    expect(output).toMatch(/"Task"/);
  });

  it("generates RoleMap interface with per-resource role unions", () => {
    const output = generateTypes(makePolicy());
    expect(output).toContain("export interface RoleMap");
    expect(output).toMatch(/Project:\s*"viewer"\s*\|\s*"editor"\s*\|\s*"admin"/);
    expect(output).toMatch(/Task:\s*"viewer"\s*\|\s*"editor"/);
  });

  it("generates PermissionMap interface with per-resource permission unions", () => {
    const output = generateTypes(makePolicy());
    expect(output).toContain("export interface PermissionMap");
    expect(output).toMatch(/Project:\s*"read"\s*\|\s*"update"\s*\|\s*"delete"\s*\|\s*"create_task"/);
    expect(output).toMatch(/Task:\s*"read"\s*\|\s*"update"\s*\|\s*"delete"/);
  });

  it("generates RelationMap interface with relation details", () => {
    const output = generateTypes(makePolicy());
    expect(output).toContain("export interface RelationMap");
    expect(output).toMatch(/Project:/);
    expect(output).toMatch(/org.*"Organization"/s);
    expect(output).toMatch(/Task:/);
    expect(output).toMatch(/project.*"Project"/s);
    expect(output).toMatch(/assignee.*"User"/s);
  });

  it("handles resources with no relations", () => {
    const policy = makePolicy({
      resources: {
        Simple: {
          roles: ["viewer"],
          permissions: ["read"],
          grants: { viewer: ["read"] },
        },
      },
    });
    const output = generateTypes(policy);
    expect(output).toContain("export interface RelationMap");
    // Simple should have an empty or Record<string, never> entry
    expect(output).toMatch(/Simple:/);
  });

  it("handles empty resources", () => {
    const policy = makePolicy({ resources: {} });
    const output = generateTypes(policy);
    expect(output).toContain("export type Actions = never");
    expect(output).toContain("export type Resources = never");
  });

  it("generates ResolverMap type with typed return values from ResourceAttributeMap", () => {
    const output = generateTypes(makePolicy());
    expect(output).toContain("export type ResolverMap");
    expect(output).not.toContain("TypedResolvers");
    expect(output).toContain("[R in Resources]?");
    expect(output).toContain("ResourceAttributeMap[R]");
    expect(output).toContain("Promise<ResourceAttributeMap[R]>");
    expect(output).not.toContain("Promise<Record<string, unknown>>");
  });

  it("generates import for TorideSchema from toride", () => {
    const output = generateTypes(makePolicy());
    expect(output).toContain('import type { TorideSchema } from "toride";');
  });

  it("generates ActorTypes union type", () => {
    const output = generateTypes(makePolicy());
    expect(output).toContain("export type ActorTypes =");
    expect(output).toMatch(/"User"/);
  });

  it("generates ActorTypes as never when no actors", () => {
    const policy = makePolicy({ actors: {} });
    const output = generateTypes(policy);
    expect(output).toContain("export type ActorTypes = never;");
  });

  it("generates ActorAttributeMap with typed attributes per actor", () => {
    const output = generateTypes(makePolicy());
    expect(output).toContain("export interface ActorAttributeMap");
    expect(output).toMatch(/User:\s*\{\s*email:\s*string;\s*department:\s*string;\s*\}/);
  });

  it("generates empty ActorAttributeMap when no actors", () => {
    const policy = makePolicy({ actors: {} });
    const output = generateTypes(policy);
    expect(output).toContain("export interface ActorAttributeMap {");
    // Should be an empty interface (just opening and closing braces)
    expect(output).toMatch(/export interface ActorAttributeMap \{\s*\}/);
  });

  it("generates ResourceAttributeMap with typed attributes per resource", () => {
    const output = generateTypes(makePolicy());
    expect(output).toContain("export interface ResourceAttributeMap");
    expect(output).toMatch(/Project:\s*\{\s*status:\s*string;\s*priority:\s*number;\s*\}/);
  });

  it("generates ResourceAttributeMap with Record<string, unknown> for resources without attributes", () => {
    const output = generateTypes(makePolicy());
    expect(output).toContain("export interface ResourceAttributeMap");
    // Task has no attributes, should fall back to Record<string, unknown>
    expect(output).toMatch(/Task:\s*Record<string, unknown>/);
  });

  it("generates GeneratedSchema extending TorideSchema", () => {
    const output = generateTypes(makePolicy());
    expect(output).toContain("export interface GeneratedSchema extends TorideSchema");
    expect(output).toMatch(/resources:\s*Resources;/);
    expect(output).toMatch(/actions:\s*Actions;/);
    expect(output).toMatch(/actorTypes:\s*ActorTypes;/);
    expect(output).toMatch(/permissionMap:\s*PermissionMap;/);
    expect(output).toMatch(/roleMap:\s*RoleMap;/);
    expect(output).toMatch(/resourceAttributeMap:\s*ResourceAttributeMap;/);
    expect(output).toMatch(/actorAttributeMap:\s*ActorAttributeMap;/);
    expect(output).toMatch(/relationMap:\s*RelationMap;/);
  });

  it("generates types in correct order", () => {
    const output = generateTypes(makePolicy());
    const importPos = output.indexOf('import type { TorideSchema }');
    const actionsPos = output.indexOf("export type Actions");
    const resourcesPos = output.indexOf("export type Resources");
    const actorTypesPos = output.indexOf("export type ActorTypes");
    const roleMapPos = output.indexOf("export interface RoleMap");
    const permissionMapPos = output.indexOf("export interface PermissionMap");
    const resourceAttrPos = output.indexOf("export interface ResourceAttributeMap");
    const actorAttrPos = output.indexOf("export interface ActorAttributeMap");
    const relationMapPos = output.indexOf("export interface RelationMap");
    const resolverMapPos = output.indexOf("export type ResolverMap");
    const generatedSchemaPos = output.indexOf("export interface GeneratedSchema");

    expect(importPos).toBeLessThan(actionsPos);
    expect(actionsPos).toBeLessThan(resourcesPos);
    expect(resourcesPos).toBeLessThan(actorTypesPos);
    expect(actorTypesPos).toBeLessThan(roleMapPos);
    expect(roleMapPos).toBeLessThan(permissionMapPos);
    expect(permissionMapPos).toBeLessThan(resourceAttrPos);
    expect(resourceAttrPos).toBeLessThan(actorAttrPos);
    expect(actorAttrPos).toBeLessThan(relationMapPos);
    expect(relationMapPos).toBeLessThan(resolverMapPos);
    expect(resolverMapPos).toBeLessThan(generatedSchemaPos);
  });

  it("maps attribute types correctly (string, number, boolean)", () => {
    const policy = makePolicy({
      actors: {
        User: { attributes: { name: "string", age: "number", active: "boolean" } },
      },
      resources: {
        Item: {
          roles: ["viewer"],
          permissions: ["read"],
          attributes: { title: "string", count: "number", published: "boolean" },
        },
      },
    });
    const output = generateTypes(policy);
    // Actor attributes
    expect(output).toMatch(/User:\s*\{\s*name:\s*string;\s*age:\s*number;\s*active:\s*boolean;\s*\}/);
    // Resource attributes
    expect(output).toMatch(/Item:\s*\{\s*title:\s*string;\s*count:\s*number;\s*published:\s*boolean;\s*\}/);
  });

  it("rejects unsafe actor type names", () => {
    const policy = makePolicy({
      actors: {
        'bad"actor': { attributes: { email: "string" } },
      },
    });
    expect(() => generateTypes(policy)).toThrow(/Unsafe identifier/);
  });

  it("rejects unsafe actor attribute field names", () => {
    const policy = makePolicy({
      actors: {
        User: { attributes: { "bad-field": "string" } },
      },
    });
    expect(() => generateTypes(policy)).toThrow(/Unsafe identifier/);
  });

  it("generates multiple actor types in ActorTypes union", () => {
    const policy = makePolicy({
      actors: {
        User: { attributes: { email: "string" } },
        ServiceAccount: { attributes: { scope: "string" } },
      },
    });
    const output = generateTypes(policy);
    expect(output).toMatch(/export type ActorTypes = "User" \| "ServiceAccount"/);
  });

  it("rejects unsafe resource attribute field names", () => {
    const policy = makePolicy({
      resources: {
        Project: {
          roles: ["viewer"],
          permissions: ["read"],
          attributes: { "bad-field": "string" },
        },
      },
    });
    expect(() => generateTypes(policy)).toThrow(/Unsafe identifier/);
  });

  it("rejects unsafe resource names with special characters", () => {
    const policy = makePolicy({
      resources: {
        'foo"; console.log("pwned");//': {
          roles: ["viewer"],
          permissions: ["read"],
        },
      },
    });
    expect(() => generateTypes(policy)).toThrow(/Unsafe identifier/);
  });

  it("rejects unsafe role names", () => {
    const policy = makePolicy({
      resources: {
        Project: {
          roles: ['admin"; //injection'],
          permissions: ["read"],
        },
      },
    });
    expect(() => generateTypes(policy)).toThrow(/Unsafe identifier/);
  });

  it("rejects unsafe permission names", () => {
    const policy = makePolicy({
      resources: {
        Project: {
          roles: ["viewer"],
          permissions: ["read\\backslash"],
        },
      },
    });
    expect(() => generateTypes(policy)).toThrow(/Unsafe identifier/);
  });

  it("rejects unsafe relation names", () => {
    const policy = makePolicy({
      resources: {
        Project: {
          roles: ["viewer"],
          permissions: ["read"],
          relations: {
            "rel-name": "Org",
          },
        },
      },
    });
    expect(() => generateTypes(policy)).toThrow(/Unsafe identifier/);
  });

  it("generates never in RoleMap for resources with no roles", () => {
    const policy = makePolicy({
      resources: {
        Webhook: {
          roles: [],
          permissions: ["trigger"],
          grants: {},
        },
      },
    });
    const output = generateTypes(policy);
    expect(output).toMatch(/Webhook:\s*never;/);
    // Verify it's inside the RoleMap block
    const roleMapBlock = output.slice(
      output.indexOf("export interface RoleMap"),
      output.indexOf("}", output.indexOf("export interface RoleMap")) + 1,
    );
    expect(roleMapBlock).toContain("Webhook: never;");
  });

  it("generates never in PermissionMap for resources with no permissions", () => {
    const policy = makePolicy({
      resources: {
        Config: {
          roles: ["admin"],
          permissions: [],
          grants: {},
        },
      },
    });
    const output = generateTypes(policy);
    const permMapBlock = output.slice(
      output.indexOf("export interface PermissionMap"),
      output.indexOf("}", output.indexOf("export interface PermissionMap")) + 1,
    );
    expect(permMapBlock).toContain("Config: never;");
  });

  it("full integration: policy exercising all codegen paths", () => {
    const policy: Policy = {
      version: "1",
      actors: {
        User: { attributes: { email: "string", active: "boolean" } },
        ServiceAccount: { attributes: { scope: "string" } },
      },
      resources: {
        Organization: {
          roles: ["owner", "member"],
          permissions: ["read", "manage"],
          attributes: { name: "string", tier: "number" },
          grants: { owner: ["all"], member: ["read"] },
        },
        Document: {
          roles: ["viewer", "editor"],
          permissions: ["read", "write", "delete"],
          attributes: { title: "string", published: "boolean" },
          relations: { org: "Organization", author: "User" },
          grants: { viewer: ["read"], editor: ["read", "write", "delete"] },
        },
        AuditLog: {
          roles: [],
          permissions: ["read"],
          grants: {},
          relations: { org: "Organization" },
        },
        EmptyResource: {
          roles: [],
          permissions: [],
          grants: {},
        },
      },
    };
    const output = generateTypes(policy);

    // Actions: union of all unique permissions across resources
    expect(output).toContain("export type Actions =");
    for (const action of ["read", "manage", "write", "delete"]) {
      expect(output).toContain(`"${action}"`);
    }

    // Resources: union of all resource names
    for (const res of ["Organization", "Document", "AuditLog", "EmptyResource"]) {
      expect(output).toContain(`"${res}"`);
    }

    // ActorTypes: both actors
    expect(output).toMatch(/"User"/);
    expect(output).toMatch(/"ServiceAccount"/);

    // RoleMap: roles per resource, never for empty
    expect(output).toMatch(/Organization:\s*"owner"\s*\|\s*"member"/);
    expect(output).toMatch(/Document:\s*"viewer"\s*\|\s*"editor"/);
    // AuditLog and EmptyResource have no roles
    const roleMapStart = output.indexOf("export interface RoleMap");
    const roleMapEnd = output.indexOf("}", roleMapStart) + 1;
    const roleMap = output.slice(roleMapStart, roleMapEnd);
    expect(roleMap).toMatch(/AuditLog:\s*never/);
    expect(roleMap).toMatch(/EmptyResource:\s*never/);

    // PermissionMap: permissions per resource, never for empty
    const permMapStart = output.indexOf("export interface PermissionMap");
    const permMapEnd = output.indexOf("}", permMapStart) + 1;
    const permMap = output.slice(permMapStart, permMapEnd);
    expect(permMap).toMatch(/Organization:\s*"read"\s*\|\s*"manage"/);
    expect(permMap).toMatch(/EmptyResource:\s*never/);

    // ResourceAttributeMap: typed for Organization/Document, Record<string, unknown> for others
    expect(output).toMatch(/Organization:\s*\{\s*name:\s*string;\s*tier:\s*number;\s*\}/);
    expect(output).toMatch(/Document:\s*\{\s*title:\s*string;\s*published:\s*boolean;\s*\}/);
    expect(output).toMatch(/AuditLog:\s*Record<string, unknown>/);
    expect(output).toMatch(/EmptyResource:\s*Record<string, unknown>/);

    // ActorAttributeMap: typed for both actors
    expect(output).toMatch(/User:\s*\{\s*email:\s*string;\s*active:\s*boolean;\s*\}/);
    expect(output).toMatch(/ServiceAccount:\s*\{\s*scope:\s*string;\s*\}/);

    // RelationMap: Document has relations, EmptyResource has none
    expect(output).toMatch(/org:\s*"Organization"/);
    expect(output).toMatch(/author:\s*"User"/);
    // Extract the full RelationMap block (contains nested braces, so find the matching closing line)
    const relationMapStart = output.indexOf("export interface RelationMap");
    const relationMapSection = output.slice(relationMapStart, output.indexOf("export type ResolverMap"));
    expect(relationMapSection).toMatch(/EmptyResource:\s*Record<string, never>/);

    // GeneratedSchema: all 8 properties present
    const schemaBlock = output.slice(output.indexOf("export interface GeneratedSchema"));
    expect(schemaBlock).toContain("resources: Resources;");
    expect(schemaBlock).toContain("actions: Actions;");
    expect(schemaBlock).toContain("actorTypes: ActorTypes;");
    expect(schemaBlock).toContain("permissionMap: PermissionMap;");
    expect(schemaBlock).toContain("roleMap: RoleMap;");
    expect(schemaBlock).toContain("resourceAttributeMap: ResourceAttributeMap;");
    expect(schemaBlock).toContain("actorAttributeMap: ActorAttributeMap;");
    expect(schemaBlock).toContain("relationMap: RelationMap;");

    // Balanced braces
    const openBraces = (output.match(/{/g) || []).length;
    const closeBraces = (output.match(/}/g) || []).length;
    expect(openBraces).toBe(closeBraces);
  });

  it("produces valid TypeScript (no syntax errors)", () => {
    const output = generateTypes(makePolicy());
    // Basic structural checks
    expect(output).toMatch(/^\/\//m); // Has comment
    const openBraces = (output.match(/{/g) || []).length;
    const closeBraces = (output.match(/}/g) || []).length;
    expect(openBraces).toBe(closeBraces); // Balanced braces
  });

  // T033: Nested object attributes
  it("generates nested object attribute types", () => {
    const policy = makePolicy({
      resources: {
        Project: {
          roles: ["viewer"],
          permissions: ["read"],
          attributes: {
            address: {
              kind: "object",
              fields: {
                city: { kind: "primitive", type: "string" },
                zip: { kind: "primitive", type: "string" },
              },
            },
          },
        },
      },
    });
    const output = generateTypes(policy);
    expect(output).toMatch(/address:\s*\{\s*city:\s*string;\s*zip:\s*string;\s*\}/);
  });

  // T034: Primitive array attributes
  it("generates primitive array attribute types", () => {
    const policy = makePolicy({
      resources: {
        Project: {
          roles: ["viewer"],
          permissions: ["read"],
          attributes: {
            tags: {
              kind: "array",
              items: { kind: "primitive", type: "string" },
            },
          },
        },
      },
    });
    const output = generateTypes(policy);
    expect(output).toMatch(/tags:\s*string\[\]/);
  });

  // T035: Array-of-objects attributes
  it("generates array-of-objects attribute types", () => {
    const policy = makePolicy({
      resources: {
        Team: {
          roles: ["member"],
          permissions: ["read"],
          attributes: {
            members: {
              kind: "array",
              items: {
                kind: "object",
                fields: {
                  id: { kind: "primitive", type: "string" },
                  role: { kind: "primitive", type: "string" },
                },
              },
            },
          },
        },
      },
    });
    const output = generateTypes(policy);
    expect(output).toMatch(/members:\s*Array<\{\s*id:\s*string;\s*role:\s*string;\s*\}>/);
  });

  // T036: Mixed flat + nested attributes
  it("generates mixed flat and nested attribute types", () => {
    const policy = makePolicy({
      resources: {
        Project: {
          roles: ["viewer"],
          permissions: ["read"],
          attributes: {
            name: "string",
            priority: "number",
            address: {
              kind: "object",
              fields: {
                city: { kind: "primitive", type: "string" },
                zip: { kind: "primitive", type: "string" },
              },
            },
            tags: {
              kind: "array",
              items: { kind: "primitive", type: "string" },
            },
          },
        },
      },
    });
    const output = generateTypes(policy);
    expect(output).toMatch(/name:\s*string/);
    expect(output).toMatch(/priority:\s*number/);
    expect(output).toMatch(/address:\s*\{\s*city:\s*string;\s*zip:\s*string;\s*\}/);
    expect(output).toMatch(/tags:\s*string\[\]/);
  });
});
