// T098: @toride/codegen generator
// Generates TypeScript type declarations from a toride Policy

import type { Policy, ResourceBlock } from "toride";

/**
 * Generate TypeScript type declarations from a toride policy.
 *
 * Emits:
 * - Actions: union of all unique permission strings
 * - Resources: union of all resource type names
 * - RoleMap: per-resource role union types
 * - PermissionMap: per-resource permission union types
 * - RelationMap: per-resource relation details
 * - TypedRelationResolver: typed resolver interface
 */
export function generateTypes(policy: Policy): string {
  const resourceNames = Object.keys(policy.resources);
  const lines: string[] = [];

  lines.push("// Auto-generated by @toride/codegen — do not edit");
  lines.push("");

  // Collect all unique actions and resource names
  const allActions = new Set<string>();
  for (const block of Object.values(policy.resources)) {
    for (const perm of block.permissions) {
      allActions.add(perm);
    }
  }

  // Actions type
  lines.push(`/** All action strings declared across all resources */`);
  if (allActions.size === 0) {
    lines.push("export type Actions = never;");
  } else {
    const actionUnion = [...allActions].map((a) => `"${a}"`).join(" | ");
    lines.push(`export type Actions = ${actionUnion};`);
  }
  lines.push("");

  // Resources type
  lines.push(`/** All resource type names */`);
  if (resourceNames.length === 0) {
    lines.push("export type Resources = never;");
  } else {
    const resourceUnion = resourceNames.map((r) => `"${r}"`).join(" | ");
    lines.push(`export type Resources = ${resourceUnion};`);
  }
  lines.push("");

  // RoleMap
  lines.push(`/** Per-resource role types */`);
  lines.push(`export interface RoleMap {`);
  for (const [name, block] of Object.entries(policy.resources)) {
    if (block.roles.length > 0) {
      const roleUnion = block.roles.map((r) => `"${r}"`).join(" | ");
      lines.push(`  ${name}: ${roleUnion};`);
    } else {
      lines.push(`  ${name}: never;`);
    }
  }
  lines.push(`}`);
  lines.push("");

  // PermissionMap
  lines.push(`/** Per-resource permission types */`);
  lines.push(`export interface PermissionMap {`);
  for (const [name, block] of Object.entries(policy.resources)) {
    if (block.permissions.length > 0) {
      const permUnion = block.permissions.map((p) => `"${p}"`).join(" | ");
      lines.push(`  ${name}: ${permUnion};`);
    } else {
      lines.push(`  ${name}: never;`);
    }
  }
  lines.push(`}`);
  lines.push("");

  // RelationMap
  lines.push(`/** Relation map — resource type -> relation name -> target info */`);
  lines.push(`export interface RelationMap {`);
  for (const [name, block] of Object.entries(policy.resources)) {
    const relations = block.relations ?? {};
    const relEntries = Object.entries(relations);
    if (relEntries.length === 0) {
      lines.push(`  ${name}: Record<string, never>;`);
    } else {
      lines.push(`  ${name}: {`);
      for (const [relName, relDef] of relEntries) {
        lines.push(`    ${relName}: { type: "${relDef.resource}"; cardinality: "${relDef.cardinality}" };`);
      }
      lines.push(`  };`);
    }
  }
  lines.push(`}`);
  lines.push("");

  // TypedRelationResolver
  lines.push(`/** Typed relation resolver — TypeScript errors if you miss a relation */`);
  lines.push(`export interface TypedRelationResolver {`);
  lines.push(`  getRelated<R extends keyof RelationMap>(`);
  lines.push(`    resource: { type: R; id: string },`);
  lines.push(`    relation: keyof RelationMap[R]`);
  lines.push(`  ): Promise<{ type: string; id: string } | { type: string; id: string }[]>;`);
  lines.push(``);
  lines.push(`  getRoles(`);
  lines.push(`    actor: { type: string; id: string; attributes: Record<string, unknown> },`);
  lines.push(`    resource: { type: string; id: string }`);
  lines.push(`  ): Promise<string[]>;`);
  lines.push(``);
  lines.push(`  getAttributes(`);
  lines.push(`    ref: { type: string; id: string }`);
  lines.push(`  ): Promise<Record<string, unknown>>;`);
  lines.push(`}`);
  lines.push("");

  return lines.join("\n");
}
