/**
 * Contract: @toride/codegen output format after redesign.
 *
 * Example of what the codegen should produce for a policy with
 * Document and Organization resources.
 */

// Auto-generated by @toride/codegen -- do not edit

/** All action strings declared across all resources */
export type Actions = "read" | "update" | "delete" | "manage";

/** All resource type names */
export type Resources = "Document" | "Organization";

/** Per-resource role types */
export interface RoleMap {
  Document: "owner" | "editor" | "viewer";
  Organization: "admin" | "member";
}

/** Per-resource permission types */
export interface PermissionMap {
  Document: "read" | "update" | "delete";
  Organization: "manage" | "read";
}

/** Relation map -- resource type -> relation name -> target type (simplified) */
export interface RelationMap {
  Document: {
    org: "Organization";
  };
  Organization: Record<string, never>;
}

/** Per-type resolver map -- TypeScript ensures all resource types have resolvers */
export type ResolverMap = {
  [R in Resources]?: (
    ref: { type: R; id: string; attributes?: Record<string, unknown> },
  ) => Promise<Record<string, unknown>>;
};
