import assert from 'node:assert/strict';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { evidence } from './support.mjs';
const core = await import('toride');
const client = await import('toride/client');
const prisma = await import('@toride/prisma');
const drizzle = await import('@toride/drizzle');
const codegen = await import('@toride/codegen');
await import('@prisma/adapter-libsql');
await import('drizzle-orm/sqlite-proxy');
assert(Number(process.versions.node.split('.')[0]) >= 20, 'Node 20 or later is required');
for (const fn of [core.Toride, core.loadJson, client.TorideClient, prisma.createPrismaAdapter, prisma.createPrismaResolver, drizzle.createDrizzleAdapter, drizzle.createDrizzleResolver, codegen.generateTypes]) assert.equal(typeof fn, 'function');
const python = spawnSync('python3', ['-c', 'import sqlite3; print(sqlite3.sqlite_version)'], { encoding: 'utf8' });
assert.equal(python.status, 0, python.stderr);
const report = { ready: true, imports: ['toride', 'toride/client', '@toride/prisma', '@toride/drizzle', '@toride/codegen'], node: process.version, sqlite: python.stdout.trim() };
writeFileSync(join(evidence, 'doctor.json'), JSON.stringify(report, null, 2) + '\n');
console.log(JSON.stringify(report));
